/**
 * ──────────────────────────────────────────────────────────────────────────────
 * API Endpoints — Aligned with neop-backend-base
 *
 * Route structure from routes/api/routes.php:
 *   /api/auth/...        → auth.php
 *   /api/{resource}/...  → features/*.php
 *   /api/temp-uploads/...         → api.php (global)
 * 
 * Note: Resource CRUD endpoints are auto-generated by createService(),
 * so only auth + shared endpoints are defined here.
 * ──────────────────────────────────────────────────────────────────────────────
 */
/** API version prefix — matches backend route aggregator */
export const API_ENDPOINTS = {
  // ── Auth (routes/api/auth.php) ─────────────────────────────────
  AUTH: {
    CONFIG: `/auth/config`,
    LOGIN: `/auth/login`,
    LOGOUT: `/auth/logout`,
    ME: `/auth/me`,
    // OTP
    OTP_VERIFY: `/auth/otp/verify`,
    OTP_RESEND: `/auth/otp/resend`,
    // Password Reset (3-step)
    PASSWORD_FORGOT: `/auth/password/forgot`,
    PASSWORD_VERIFY_OTP: `/auth/password/verify-otp`,
    PASSWORD_RESET: `/auth/password/reset`,
    // Change Password (protected)
    PASSWORD_CHANGE: `/auth/password/change`,
    PASSWORD_CHANGE_VERIFY: `/auth/password/change/verify`,
    // TOTP (protected)
    TOTP_SETUP: `/auth/totp/setup`,
    TOTP_CONFIRM: `/auth/totp/confirm`,
    TOTP_DISABLE: `/auth/totp/disable`,
  },
  // ── Resources (auto-generated by createService) ─────────────────────────
  // Usage: createService<User>(`/users`)
  // No need to define CRUD endpoints here — createService handles them.
  /** Helper: Build a resource base URL */
  resource: (name: string) => `/${name}`,
  // ── Temp Uploads (routes/api.php — global) ──────────────────────────────
  TEMP_UPLOADS: {
    STORE: '/api/temp-uploads',
    UPLOAD: '/api/temp-uploads',
    SHOW: (token: string) => `/api/temp-uploads/${token}`,
    GET: (token: string) => `/api/temp-uploads/${token}`,
    DESTROY: (token: string) => `/api/temp-uploads/${token}`,
    DELETE: (token: string) => `/api/temp-uploads/${token}`,
  },
  // ── Dashboard ───────────────────────────────────────────────────────────
  DASHBOARD: `/dashboard`,

  // ── CMS Headless ────────────────────────────────────────────────────────
  CMS: {
    // Pages
    PAGES: '/cms/pages',
    PAGE: (id: number | string) => `/cms/pages/${id}`,
    PAGE_PUBLISH: (id: number | string) => `/cms/pages/${id}/publish`,
    PAGE_UNPUBLISH: (id: number | string) => `/cms/pages/${id}/unpublish`,
    PAGE_DUPLICATE: (id: number | string) => `/cms/pages/${id}/duplicate`,
    PAGE_CONTENT_BATCH: (id: number | string) => `/cms/pages/${id}/content/batch`,

    // Sections
    SECTIONS: (pageId: number | string) => `/cms/pages/${pageId}/sections`,
    SECTION: (pageId: number | string, sectionId: number | string) =>
      `/cms/pages/${pageId}/sections/${sectionId}`,
    SECTIONS_REORDER: '/cms/sections/reorder',
    SECTION_TOGGLE: (sectionId: number | string) => `/cms/sections/${sectionId}/toggle`,

    // Section Content
    SECTION_CONTENT: (sectionId: number | string) => `/cms/sections/${sectionId}/content`,
    SECTION_CONTENT_LOCALE: (sectionId: number | string, locale: string) =>
      `/cms/sections/${sectionId}/content/${locale}`,
    SECTION_CONTENT_BATCH: (sectionId: number | string) =>
      `/cms/sections/${sectionId}/content/batch`,
    SECTION_CONTENT_PUBLISH: (sectionId: number | string) =>
      `/cms/sections/${sectionId}/content/publish`,
    SECTION_CONTENT_PREVIEW: (sectionId: number | string) =>
      `/cms/sections/${sectionId}/content/preview`,

    // Reusable Library
    REUSABLE: '/cms/reusable',
    REUSABLE_ITEM: (id: number | string) => `/cms/reusable/${id}`,
    REUSABLE_REORDER: '/cms/reusable/reorder',
    REUSABLE_TOGGLE: (id: number | string) => `/cms/reusable/${id}/toggle`,
    REUSABLE_CONTENT: (id: number | string) => `/cms/reusable/${id}/content`,
    REUSABLE_CONTENT_BATCH: (id: number | string) => `/cms/reusable/${id}/content/batch`,
    REUSABLE_CONTENT_PUBLISH: (id: number | string) => `/cms/reusable/${id}/content/publish`,
    REUSABLE_CONTENT_PREVIEW: (id: number | string) => `/cms/reusable/${id}/content/preview`,

    // SEO
    PAGE_SEO: (pageId: number | string) => `/cms/pages/${pageId}/seo`,
    PAGE_SEO_LOCALE: (pageId: number | string, locale: string) =>
      `/cms/pages/${pageId}/seo/${locale}`,
    PAGE_SEO_BATCH: (pageId: number | string) => `/cms/pages/${pageId}/seo/batch`,

    // Config
    RELATION_MODELS: '/cms/relation-models',
    BUILDER_STATUS: '/cms/builder/status',
  },

  // ── Static Pages (Content) ──────────────────────────────────────────────
  STATIC_PAGES: {
    LIST: '/static-pages',
  },
} as const
export type ApiEndpoint = typeof API_ENDPOINTS
