import type { JiraIssue } from './jira'

/**
 * Converts a JiraIssue object into a full Markdown string.
 */
export function issueToMarkdown(issue: JiraIssue): string {
  const f = issue.fields
  const lines: string[] = []

  // Title
  lines.push(`# [${issue.key}] ${f.summary}`)
  lines.push('')

  // Metadata table
  lines.push('## Details')
  lines.push('')
  lines.push(`| Field | Value |`)
  lines.push(`|-------|-------|`)
  lines.push(`| **Key** | \`${issue.key}\` |`)
  lines.push(`| **Type** | ${f.issuetype?.name ?? '-'} |`)
  lines.push(`| **Status** | ${f.status?.name ?? '-'} |`)
  lines.push(`| **Priority** | ${f.priority?.name ?? '-'} |`)
  lines.push(`| **Assignee** | ${f.assignee?.displayName ?? 'Unassigned'} |`)
  lines.push(`| **Reporter** | ${f.reporter?.displayName ?? '-'} |`)
  lines.push(`| **Created** | ${formatDate(f.created)} |`)
  lines.push(`| **Updated** | ${formatDate(f.updated)} |`)
  if (f.duedate)
    lines.push(`| **Due Date** | ${f.duedate} |`)
  if (f.components?.length) {
    lines.push(`| **Components** | ${f.components.map((c: any) => c.name).join(', ')} |`)
  }
  if (f.fixVersions?.length) {
    lines.push(`| **Fix Version** | ${f.fixVersions.map((v: any) => v.name).join(', ')} |`)
  }
  lines.push('')

  // Labels
  if (f.labels?.length) {
    lines.push('## Labels')
    lines.push('')
    lines.push(f.labels.map((l: string) => `\`${l}\``).join(' '))
    lines.push('')
  }

  // Description
  lines.push('## Description')
  lines.push('')
  if (f.description) {
    lines.push(adfToMarkdown(f.description))
  }
  else {
    lines.push('_No description provided._')
  }
  lines.push('')

  // Subtasks
  if (f.subtasks?.length) {
    lines.push('## Subtasks')
    lines.push('')
    for (const sub of f.subtasks) {
      lines.push(`- [ ] **${sub.key}** — ${sub.fields.summary} *(${sub.fields.status?.name})*`)
    }
    lines.push('')
  }

  // Comments
  const comments = f.comment?.comments ?? []
  if (comments.length > 0) {
    lines.push('## Comments')
    lines.push('')
    for (const c of comments) {
      lines.push(`### 💬 ${c.author?.displayName ?? 'Unknown'} — ${formatDate(c.created)}`)
      lines.push('')
      lines.push(adfToMarkdown(c.body))
      lines.push('')
    }
  }

  // Footer
  lines.push('---')
  lines.push(`> Generated by jira-to-md on ${new Date().toISOString()}`)

  return lines.join('\n')
}

/**
 * Converts Atlassian Document Format (ADF) JSON to Markdown text.
 * Jira stores description/comment body as ADF - this handles the
 * most common node types.
 */
function adfToMarkdown(node: any, depth = 0): string {
  if (!node)
    return ''

  // Plain string (shouldn't happen in ADF but just in case)
  if (typeof node === 'string')
    return node

  const indent = '  '.repeat(depth)

  switch (node.type) {
    case 'doc':
      return (node.content ?? []).map((n: any) => adfToMarkdown(n, depth)).join('\n')

    case 'paragraph':
      return `${(node.content ?? []).map((n: any) => adfToMarkdown(n, depth)).join('')}\n`

    case 'text': {
      let text = node.text ?? ''
      const marks: string[] = (node.marks ?? []).map((m: any) => m.type)
      if (marks.includes('strong'))
        text = `**${text}**`
      if (marks.includes('em'))
        text = `_${text}_`
      if (marks.includes('code'))
        text = `\`${text}\``
      if (marks.includes('strike'))
        text = `~~${text}~~`
      if (marks.includes('underline'))
        text = `<u>${text}</u>`
      const linkMark = (node.marks ?? []).find((m: any) => m.type === 'link')
      if (linkMark)
        text = `[${text}](${linkMark.attrs?.href ?? '#'})`
      return text
    }

    case 'hardBreak':
      return '\n'

    case 'heading': {
      const level = node.attrs?.level ?? 1
      const prefix = '#'.repeat(Math.min(level + 1, 6)) // offset by 1 since h1 is the title
      const content = (node.content ?? []).map((n: any) => adfToMarkdown(n)).join('')
      return `${prefix} ${content}\n`
    }

    case 'bulletList':
      return `${(node.content ?? [])
        .map((n: any) => `${indent}- ${adfToMarkdown(n, depth + 1).trim()}`)
        .join('\n')}\n`

    case 'orderedList':
      return `${(node.content ?? [])
        .map((n: any, i: number) => `${indent}${i + 1}. ${adfToMarkdown(n, depth + 1).trim()}`)
        .join('\n')}\n`

    case 'listItem':
      return (node.content ?? []).map((n: any) => adfToMarkdown(n, depth)).join('').trim()

    case 'codeBlock': {
      const lang = node.attrs?.language ?? ''
      const code = (node.content ?? []).map((n: any) => n.text ?? '').join('')
      return `\`\`\`${lang}\n${code}\n\`\`\`\n`
    }

    case 'blockquote':
      return `${(node.content ?? [])
        .map((n: any) => `> ${adfToMarkdown(n, depth).trim()}`)
        .join('\n')}\n`

    case 'rule':
      return '---\n'

    case 'table': {
      const rows: any[] = node.content ?? []
      if (rows.length === 0)
        return ''
      const mdRows: string[] = []
      rows.forEach((row: any, i: number) => {
        const cells = (row.content ?? []).map((cell: any) =>
          (cell.content ?? []).map((n: any) => adfToMarkdown(n).trim()).join(' '),
        )
        mdRows.push(`| ${cells.join(' | ')} |`)
        if (i === 0) {
          mdRows.push(`| ${cells.map(() => '---').join(' | ')} |`)
        }
      })
      return `${mdRows.join('\n')}\n`
    }

    case 'inlineCard':
    case 'blockCard': {
      const url = node.attrs?.url ?? '#'
      return `[${url}](${url})`
    }

    case 'mention': {
      const name = node.attrs?.text ?? node.attrs?.id ?? 'mention'
      return `@${name}`
    }

    case 'emoji':
      return node.attrs?.text ?? node.attrs?.shortName ?? ''

    case 'mediaGroup':
    case 'mediaSingle':
    case 'media':
      return `_[Attachment: ${node.attrs?.alt ?? node.attrs?.id ?? 'media'}]_`

    default:
      // Fallback: try to extract any nested text
      if (node.content) {
        return (node.content as any[]).map((n: any) => adfToMarkdown(n, depth)).join('')
      }
      return ''
  }
}

function formatDate(iso: string): string {
  if (!iso)
    return '-'
  return new Date(iso).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}
