/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineFilters: typeof import('./composables/shared/useFilters').defineFilters
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const initializeDarkMode: typeof import('./composables/shared/useDarkMode').initializeDarkMode
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAdmins: typeof import('./composables/admins/useAdmins').useAdmins
  const useAttrs: typeof import('vue').useAttrs
  const useAuth: typeof import('./composables/shared/useAuth').useAuth
  const useAuthStore: typeof import('./stores/shared/authStore').useAuthStore
  const useBreadcrumb: typeof import('./composables/shared/useBreadcrumb').useBreadcrumb
  const useCan: typeof import('./composables/shared/useCan').useCan
  const useColumnVisibility: typeof import('./composables/shared/useColumnVisibility').useColumnVisibility
  const useConfirm: typeof import('./composables/shared/useConfirm').useConfirm
  const useContextMenu: typeof import('./composables/shared/useContextMenu').useContextMenu
  const useContextMenuPortal: typeof import('./composables/shared/useContextMenu').useContextMenuPortal
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDarkMode: typeof import('./composables/shared/useDarkMode').useDarkMode
  const useDashboardStore: typeof import('./stores/shared/dashboard').useDashboardStore
  const useDetails: typeof import('./composables/shared/useDetails').useDetails
  const useFileUpload: typeof import('./composables/shared/useFileUpload').useFileUpload
  const useFilterStore: typeof import('./stores/shared/filter').useFilterStore
  const useForm: typeof import('./composables/shared/useForm').useForm
  const useFormatter: typeof import('./composables/shared/useFormatter').useFormatter
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useImportExport: typeof import('./composables/shared/useImportExport').useImportExport
  const useLink: typeof import('vue-router').useLink
  const useModal: typeof import('./composables/shared/useModal').useModal
  const useModel: typeof import('vue').useModel
  const useMouse: typeof import('@vueuse/core').useMouse
  const useMyFetch: typeof import('@vueuse/core').useFetch
  const useNotificationStore: typeof import('./stores/shared/notification').useNotificationStore
  const useNotifications: typeof import('./composables/notifications/useNotifications').useNotifications
  const usePageHeader: typeof import('./composables/shared/usePageHeader').usePageHeader
  const usePdf: typeof import('./stores/shared/usePdf').usePdf
  const usePermissionStore: typeof import('./stores/shared/permissions').usePermissionStore
  const usePusher: typeof import('./composables/shared/usePusher').usePusher
  const usePwaInstall: typeof import('./composables/shared/usePwaInstall').usePwaInstall
  const useRoles: typeof import('./composables/roles/useRoles').useRoles
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSearchablePages: typeof import('./composables/shared/useSearchablePages').useSearchablePages
  const useSlots: typeof import('vue').useSlots
  const useSonarStore: typeof import('./stores/shared/sonar').useSonarStore
  const useTable: typeof import('./composables/shared/useTable').useTable
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { Formatter, UseFormatterOptions } from './composables/shared/useFormatter'
  import('./composables/shared/useFormatter')
  // @ts-ignore
  export type { BreadcrumbItem } from './composables/shared/useBreadcrumb'
  import('./composables/shared/useBreadcrumb')
  // @ts-ignore
  export type { ColumnConfig, ColumnDef } from './composables/shared/useColumnVisibility'
  import('./composables/shared/useColumnVisibility')
  // @ts-ignore
  export type { ConfirmState } from './composables/shared/useConfirm'
  import('./composables/shared/useConfirm')
  // @ts-ignore
  export type { ContextMenuAction } from './composables/shared/useContextMenu'
  import('./composables/shared/useContextMenu')
  // @ts-ignore
  export type { FileWithStatus } from './composables/shared/useFileUpload'
  import('./composables/shared/useFileUpload')
  // @ts-ignore
  export type { FilterFieldShorthand } from './composables/shared/useFilters'
  import('./composables/shared/useFilters')
  // @ts-ignore
  export type { UseFormOptions } from './composables/shared/useForm'
  import('./composables/shared/useForm')
  // @ts-ignore
  export type { PageHeaderPayload } from './composables/shared/usePageHeader'
  import('./composables/shared/usePageHeader')
  // @ts-ignore
  export type { SearchablePage } from './composables/shared/useSearchablePages'
  import('./composables/shared/useSearchablePages')
  // @ts-ignore
  export type { DashboardPOV } from './stores/shared/dashboard'
  import('./stores/shared/dashboard')
  // @ts-ignore
  export type { NotificationItem } from './stores/shared/notification'
  import('./stores/shared/notification')
  // @ts-ignore
  export type { SonarType, SonarMessage } from './stores/shared/sonar'
  import('./stores/shared/sonar')
}
